### ISSUE TITLE
the ignorePattern option of max-len rule seems not work for prettier-eslint

### ISSUE THREAD

**Issue by fatfatson** [prettier/prettier-eslint#162]
sometimes, I don't want html tag to be formatted as multilines, inspite of how many attributes it has.
eslint itself could recoginze the rule below, but prettier-eslint ignores it and always produces multilines because the 100 limit.

> 'max-len': [2, { code: 100, ignoreUrls: true, ignorePattern: '<.*>' }]

**Comment by zimme** [comment]
This is because prettier runs first and based on its `printWidth` option wraps all lines at that length and eslint that runs after prettier isn't smart enough to undo the multiline splits that prettier created.

If you haven't configured prettier then the `printWidth` option is inferred via `max-len`s `code` option.

So unless prettier has an option to also ignore urls or patterns for its `printWidth` option there's nothing we can do about this.
