### ISSUE TITLE
Long line length ternary statements being broken onto multiple lines

### ISSUE THREAD

**Issue by donovanhiland** [prettier/prettier-eslint#64]
Hi there,

I'm using prettier-eslint both from the cli and through the atom plugin depending on the file/project. With this eslintrc:

    {
      parser: 'babel-eslint',
      extends: 'airbnb'
    }

I get some ternary lines being formatted onto a single line, and others are being broken onto multiple lines. It looks like the lines being broken are those over 100 characters. Any ideas why this might be happening and how I can fix it so all ternary statements are single line?

I've tried setting `'multiline-ternary': [2, 'never']` in the rules with no change. I was also trying to extend a different eslint config from standardjs in which case ternary lines aren't being formatted at all regardless of the rules I have set. Is there a prettier config for ternary?

**Comment by kentcdodds** [comment]
This is because `prettier` doesn't have any sort of configuration for ternary. So when prettier runs over your code it formats it nicely however it needs to to be consistent. Then when ESLint comes along, it is unable to fix it (because that particular rule is unfixable). I recommend disabling the rule and just going with whatever prettier does.
