### ISSUE TITLE
how to integrate with prettier vscode extension? no longer has "prettier.eslintIntegration" option

### ISSUE THREAD

**Issue by the-vampiire** [prettier/prettier-eslint#699]
hey i am wondering how to properly integrate this with vscode now?

i am able to run it with an NPM script but would like to set is for formatting on save.

thank you for writing this by the way!

**Comment by NoelDeMartin** [comment]
I've been looking into this, and it seems like [this was removed about 3 years ago](https://github.com/prettier/prettier-vscode/issues/922) from the vscode plugin. And I haven't been able to find a replacement. They point to this message [in the README](https://github.com/prettier/prettier-vscode#linter-integration) as a solution:

> The recommended way of integrating with linters is to let Prettier do the formatting and configure the linter to not deal with formatting rules. You can find instructions on how to configure each linter on the Prettier docs site. You can then use each of the linting extensions as you normally would. For details refere to the [Prettier documentation](https://prettier.io/docs/en/integrating-with-linters.html).

So it seems like this is a use-case that is no longer supported (which is a bit confusing, because if you visit the Prettier documentation it leads you back here).

I had given up all hope at this point, but it ocurred to me that this project still seems to work on the CLI. Looking for a way to run this script on save, I found the following VSCode plugin [Custom Local Formatters](https://marketplace.visualstudio.com/items?itemName=jkillian.custom-local-formatters). You also need to install the [prettier-eslint-cli](https://github.com/prettier/prettier-eslint-cli) package, but once you've done that, it seems to work with the following config:

```json
"editor.defaultFormatter": "jkillian.custom-local-formatters",
"editor.formatOnSave": true,
"customLocalFormatters.formatters": [
    {
        "command": "prettier-eslint --parser typescript --stdin",
        "languages": ["ts"]
    }
]
```

You'll need to configure this differently for other languages, but so far it gets the job done :). Happy to hear if there's any better options though.

**Comment by drewbaker** [comment]
Yeah I'm moving to VS Code after Atom end of life, and finding it really difficult to get this working too.

**Comment by idahogurl** [comment]
I'm going to do a unapologetic plug for my extention. [VS Code Prettier ESLint](https://marketplace.visualstudio.com/items?itemName=rvest.vs-code-prettier-eslint)

**Comment by drewbaker** [comment]
@idahogurl im way ahead of you. That totally was the answer and I even wrote up some docs for my team to follow: https://paper.dropbox.com/doc/How-to-get-VS-Code-setup--BkGlDyauC~UZtwk4iPO83e~yAQ-38r84QublFNAzo74LSCwf?_tk=slack_preview

**Comment by JounQin** [comment]
Close in favor of https://github.com/idahogurl/vs-code-prettier-eslint
