### ISSUE TITLE
Do not shorten the (slightly) longer lines

### ISSUE THREAD

**Issue by dacz** [prettier/prettier-eslint#85]
I posted this issue to prettier-atom and then on the recommendation tried to process these issues with prettier-eslint-cli with the same output, therefore I'm landing them here:

prettier-eslint-cli version: 3.4.4
node: v7.9.0
yarn: 0.24.4

Example: 

`const enhWithZip = withProps(props => ({ zip: path([ 'place', 'zip' ], props) }));`

Setting is 80char wide (this is 83). Cannot make it shorter. When I make it one character longer, it works:

```
const enhWithZip = withProps(props => ({
  zip: path([ 'place', 'zipa' ], props),
}));
```

My eslint is set to require spaces inside brackets `{ ... }` and `[ ... ]`. 

---

another issue:

Deeply nested (complexity 29, booooo, shame on me but this component should be like this) snippet:

```
              <tr
                className={ place && place.streetAndSublocality ? '' : 'invalid' }
              >
```
length 83 (again).

I change this manually to:

```
              <tr
                className={
                  place && place.streetAndSublocality ? '' : 'invalid'
                }
              >
```
and similar modifications but save (reformat on save) will change it again to 83 long one line to disturb eslint. No problem with disable-line but... :)

... unfortunatelly problem with eslint...

I fixed my complexity ugliness with disable-line

`const Summary = ({ priceRange, place, order, user, intl }) => { //eslint-disable-line complexity`

but prettier reformats on save:

```
const Summary = ({ priceRange, place, order, user, intl }) => {
  //eslint-disable-line complexity
  const durationInHours = m...
```

that the `//eslint... ` part is on next line and therefore making eslint unhappy again.

---

Note: I went to all-prettier and format on save. Prettier rocks! Thanks.

**Comment by kentcdodds** [comment]
Yeah, this is a limitation of the way that prettier and eslint are integrated. If eslint changes anything that results in the line being too long, then that line doesn't get fixed by prettier (because prettier's already run). Even if prettier were to run last, it would just remove the extra space that eslint had added rather than break to a new line.

Because of this, we've marked this particular issue as a "wont fix."

Rather than `// eslint-disable-line`, I suggest you use `// eslint-disable-next-line` on the line above the problem line.

Good luck!
