### ISSUE TITLE
Project integration

### ISSUE THREAD

**Issue by bstro** [prettier/prettier-eslint#88]
It's not really clear to me, based on any of the current documentation, how to actually use this with a project. Is this a CLI tool? Does it require a configuration file? Is there a default location for such a configuration file? Is there an example available that shows how to hook this up with an existing set of eslint rules? I just can't quite figure out how to use this.

**Comment by kentcdodds** [comment]
Hi there! Perhaps documentation could be improved. But there is a CLI looked in the readme, also there are editor plugins as well.

**Comment by Dianna** [comment]
I had the same issue as @bstro.  Are the CLI and editor plugins essential for running prettier-eslint? Can it be run independently? If so how? The example doesn't present an even relatively realistic use case. If not, that should be made clear.

**Comment by kentcdodds** [comment]
> Are the CLI and editor plugins essential for running prettier-eslint?

For most use-cases yes. This package is for programmatically formatting a string of code. If you want to implement it in your project you should look at the CLI and editor plugins. I'm not sure how to make that more clear, but if either of you would like to [make a pull request](http://makeapullrequest.com) you're definitely welcome to do so.

I'm going to go ahead and close this issue though because I'm unsure how to make things more clear myself. Good luck!

**Comment by zimme** [comment]
@EsdrasEtrenne If you wanna run this on the command line have a look at https://github.com/prettier/prettier-eslint-cli, otherwise you can use it with prettier's vscode/atom integrations.
