### ISSUE TITLE
--list-different does not work when use --write, using prettier+prettier-eslint+prettier-eslint-cli

### ISSUE THREAD

**Issue by dzhytomyrsky** [prettier/prettier-eslint#93]
I wrote such npm script in my package.json:

`"format-js": "prettier-eslint --print-width 100 --list-different --write 'webpack/**/*.js' 'development/**/*.js'"`

it formats my js, but does not print prettified files. Is it possible to use --list-different with --write?

If not, it would be great to))

**Comment by kentcdodds** [comment]
I'm not sure whether it's possible. I don't use that feature. Could you describe your use case?

**Comment by yannickschuchmann** [comment]
Hey, @kentcdodds,
When running `prettier --list-different --write` it formats all files **and** prints all paths of prettified files.

Unfortunately prettier-eslint behaves differently.
```shell
> prettier-eslint --list-different --write "./src/**/*.js"
success formatting 28 files with prettier-eslint
14 files were unchanged
```

A **use case** would be integrating the formatting to [lintstaged](https://github.com/okonet/lint-staged#installation-and-setup). 
E.g.:
```json
"lint-staged": {
    "*.{js}": ["prettier-eslint --list-different --write \"./src/**/*.js\"", "git add"]
}
```

Here lintstaged is expecting a list of pathnames to pass it along to `git add` after formatting.

Well, I'm aware that this is not a very common use case because modifying files on precommit hook could be a dangerous thing. 
But anyways, I thought that prettier-eslint tries to provide a similar API compared to prettier. Or am I wrong? :)

I believe there are at least two options:
a) printing pathnames like I mentioned above
b) telling the user that combining `--list-different` & `--write` is not supported (yet).

What do you think?
